### ISSUE TITLE
IP不可用了

### ISSUE THREAD

**Issue by jiuyaopinyin** [zouhuanxin/BookCrawler#1]
现在IP不能用了,请问有新的IP可以使用吗?

**Comment by csiyi-a** [comment]
同问，急

**Comment by zouhuanxin** [comment]
已经更新了ip

**Comment by zouhuanxin** [comment]
已经更新了ip 请前往github查看





------------------ 原始邮件 ------------------
发件人: jiuyaopinyin ***@***.***&gt;
发送时间: 2021年4月17日 07:54
收件人: zouhuanxin/BookCrawler ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1)





 
现在IP不能用了,请问有新的IP可以使用吗?

**Comment by zouhuanxin** [comment]
已经更新了ip 请前往github查看






------------------ 原始邮件 ------------------
发件人: csiyi-a ***@***.***&gt;
发送时间: 2021年4月17日 10:18
收件人: zouhuanxin/BookCrawler ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1)





 
同问，急

**Comment by jiuyaopinyin** [comment]
> 已经更新了ip 请前往github查看
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: jiuyaopinyin ***@***.***&gt; 发送时间: 2021年4月17日 07:54 收件人: zouhuanxin/BookCrawler ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1) 现在IP不能用了,请问有新的IP可以使用吗? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好,这个新的好像还是返回301失败
http://81.70.179.4:8082/getHome

**Comment by zouhuanxin** [comment]
现在应该可以了 被防火墙拦了





------------------ 原始邮件 ------------------
发件人: jiuyaopinyin ***@***.***&gt;
发送时间: 2021年4月17日 12:31
收件人: zouhuanxin/BookCrawler ***@***.***&gt;
抄送: azou ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1)





  
已经更新了ip 请前往github查看
 …
 ------------------ 原始邮件 ------------------ 发件人: jiuyaopinyin @.&gt; 发送时间: 2021年4月17日 07:54 收件人: zouhuanxin/BookCrawler @.&gt; 抄送: Subscribed @.***&gt; 主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1) 现在IP不能用了,请问有新的IP可以使用吗? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好,这个新的好像还是返回301失败
 http://81.70.179.4:8082/getHome

**Comment by jiuyaopinyin** [comment]
> 现在应该可以了 被防火墙拦了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: jiuyaopinyin ***@***.***&gt; 发送时间: 2021年4月17日 12:31 收件人: zouhuanxin/BookCrawler ***@***.***&gt; 抄送: azou ***@***.***&gt;, State change ***@***.***&gt; 主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1) 已经更新了ip 请前往github查看 … ------------------ 原始邮件 ------------------ 发件人: jiuyaopinyin @.&gt; 发送时间: 2021年4月17日 07:54 收件人: zouhuanxin/BookCrawler @.&gt; 抄送: Subscribed @.***&gt; 主题: 回复：[zouhuanxin/BookCrawler] IP不可用了 (#1) 现在IP不能用了,请问有新的IP可以使用吗? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你好,这个新的好像还是返回301失败 http://81.70.179.4:8082/getHome — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

好像还是不行...
